### ISSUE TITLE
Detox e2e testing and app permissions

### ISSUE THREAD

**Issue by Antonhansel** [expo/detox-expo-helpers#14]
I'm referencing this issue opened on the expo main repo, especially the last part about random simulators opening if I pass parameters to `reloadApp`

https://github.com/expo/expo/issues/5790

Has any of you encountered this very strange behavior before ?

**Comment by tochman** [comment]
Not sure if it's relevant for your issue, but I'm working my way through permission issues as well. See my comment on https://github.com/expo/expo/issues/3516#issuecomment-727584640

**Comment by Antonhansel** [comment]
Hey @tochman thank you for pinging me on this.
I've moved on to other projects and migrated away from Expo, I was never able to figure out this one.
Good luck though 😬
