### ISSUE TITLE
reloadApp not working for detox version above 7.2.0

### ISSUE THREAD

**Issue by tatane616** [expo/detox-expo-helpers#8]
When running command `detox test`, `reloadApp()` not working for detox version above 7.2.0.
Less than 7.2.0, It works normally.

```package.json
"dependencies": {
    "expo": "^29.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz"
  },
  "devDependencies": {
    "detox": "7.3.0",
    "detox-expo-helpers": "^0.2.0",
    "mocha": "^4.0.1"
  },
```

I want to enable artifacts such as device logs, device screenshots and screen recordings, but it does not correspond to detox 7.2.0 or lower.
https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md
Is there any solution?

**Comment by haikyuu** [comment]
Any workarounds for this? Any way we can avoid detaching?
